/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Contact */

#ifndef _Included_Contact
#define _Included_Contact
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Contact
 * Method:    displayContacts
 * Signature: (Ljava/util/ArrayList;)V
 */
JNIEXPORT void JNICALL Java_Contact_displayContacts
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
